name: Draft Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Draft Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.BANNO_AUTOBOT_GITHUB_TOKEN }}

    - id: current_version
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: gordon-plugin/gradle.properties
        property: version

    - name: Create Tag
      uses: simpleactions/create-tag@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ steps.current_version.outputs.value }}
        message: ${{ steps.current_version.outputs.value }}

    - id: next_version
      uses: jessicalostinspace/bump-semantic-version-action@v1.0.1
      with:
        semantic-version: ${{ steps.current_version.outputs.value }}
        version-type: PATCH

    - name: Bump Version
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: gordon-plugin/gradle.properties
        property: version
        value: ${{steps.next_version.outputs.bumped-semantic-version}}

    - name: Commit Version Bump
      uses: EndBug/add-and-commit@v4.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.BANNO_AUTOBOT_GITHUB_TOKEN }}
      with:
        add: gordon-plugin/gradle.properties
        message: Bump version to ${{steps.next_version.outputs.bumped-semantic-version}}

    - name: Draft Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.current_version.outputs.value }}
        release_name: ${{ steps.current_version.outputs.value }}
        body: <!-- Generate release notes by using the "Auto-generate release notes" button above -->
        draft: true
