name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4

    - uses: actions/checkout@v4

    - name: Test
      run: ./gradlew lintKotlin test --continue
