name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11

    - uses: actions/checkout@v3

    - name: Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: lintKotlin test --continue
