name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/checkout@v2

    - name: Test
      uses: gradle/gradle-build-action@v1
      with:
        arguments: lintKotlin test --continue
