name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: 21

    - uses: gradle/actions/setup-gradle@v6
      with:
        cache-provider: basic

    - uses: actions/checkout@v6

    - name: Test
      run: ./gradlew lintKotlin test --continue
